[package]
name = "skynet-substrate"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = { version = "0.13", default-features = false }
bytes = { version = "1.1", default-features = false }
ed25519-dalek = { version = '1.0', default-features = false, features = [
	"u64_backend",
	"alloc",
] }
frame-support = { version = '3.0', default-features = false }
serde = { version = '1.0', default-features = false, features = ['derive'] }
serde_json = { version = '1.0', default-features = false, features = ['alloc'] }
sp-core = { version = '3.0', default-features = false }
sp-io = { version = '3.0', default-features = false }
sp-runtime = { version = '3.0', default-features = false }
sp-std = { version = '3.0', default-features = false }

[features]
default = ['std']
std = [
    'base64/std',
    'bytes/std',
    'ed25519-dalek/std',
	'frame-support/std',
    'sp-core/std',
    'sp-io/std',
    'sp-runtime/std',
	'sp-std/std',
]
