[package]
name = "skynet-substrate"
version = "0.1.0"
edition = "2018"

[dependencies]
frame-support = { version = '3.0', default-features = false }
sp-io = { version = '3.0', default-features = false }
sp-runtime = { version = '3.0', default-features = false }
sp-std = { version = '3.0', default-features = false }

[features]
default = ['std']
std = [
	'frame-support/std',
	'sp-io/std',
    'sp-runtime/std',
	'sp-std/std',
]
